name: Integration Test
on:
  repository_dispatch:
  workflow_dispatch:

jobs:
  build:
    name: "Labels: Test"
    env:
      JOB_NAME: ${{ github.repository }}
      BUILD_NUMBER: ${{ github.run_number }}
      CONAN_USER_HOME: ${{ github.workspace }}
      CONAN_TRACE_FILE : ${{ github.workspace }}/build_info.json
    runs-on: ubuntu-latest
    steps:
      - name: Get Conan
        uses: turtlebrowser/get-conan@v1.0
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Conan Config
        run: |
          conan remote add conan_repo ${{ secrets.ARTIFACTORY_REPOSITORY }}/artifactory/api/conan/conan-test -i 0 -f
          conan user -p ${{ secrets.ARTIFACTORY_PASSWORD }} -r conan_repo ${{ secrets.ARTIFACTORY_USERNAME }}
          conan config set artifact_property_build.name=${{ github.repository }}
          conan config set artifact_property_build.number=${{ github.run_number }}
          conan config set artifact_property_build.timestamp=${{ date "+%Y-%m-%d-%H:%M" }}
      - name: Build
        run: |
          conan upload ${{ github.event.repository.name }}/0.1.0@aev25/stable -r conan_repo --all
          conan_build_info --v2 create buildinfo.json --lockfile conan.lock --user ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD }}
          conan_build_info --v2 publish buildinfo.json --url http://localhost:8081/artifactory --user ${{ secrets.ARTIFACTORY_USERNAME }} --password ${{ secrets.ARTIFACTORY_PASSWORD }}
      - name: Upload build informatio
        run: |
          curl -X PUT -u ${{ secrets.ARTIFACTORY_USERNAME }}:${{ secrets.ARTIFACTORY_PASSWORD }} -H "Content-type: application/json" -T /tmp/build_info.json "${{ secrets.ARTIFACTORY_REPOSITORY }}/artifactory/api/build"
